### ISSUE TITLE
Getting this error when directive execute ngChange

### ISSUE THREAD

**Issue by elcomjc** [Ahimta/bc-phone-number#15] opened 2016-06-17 18:13 UTC
TypeError: scope.ngChange is not a function.

ngChange is defined on the directive, but is a reserved word in angularJS.

**Comment by dmbjsn** [comment] 2016-06-19 20:56
Hi @elcomjc,

I've experienced the same issue. The problem is that the `ngChange` attribute should be assigned as a function/expression trigger in the isolate scope of the 'bcPhoneNumber' directive, and it is right now being assigned as a two-way bound variable.

You can solve this by changing line 45 (dist/js/bc-phone-number.js, v. 5.0.12) from this:
`ngChange: '='`

...to this:
`ngChange: '&'`

Hope this helps you. 

@Sjors, maybe this is something to consider for the next release along with #14? I'm getting errors in ng 1.5+ if I don't apply these two changes. Thanks for a nice lib.

**Comment by elcomjc** [comment] 2016-09-22 15:39
Hi @dmbjsn ,

Yeah with that change i resolve the problem too.

i think you guys @Sjors have to include this on the next realease of the lib.

Thank you very much!

**Comment by jtormey** [comment] 2016-10-24 17:40
Fixed in v5.1

**Closed as completed by jtormey** 2016-10-24 17:40 UTC
